name: Test Build Docker

on:
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ github.repository }}:test
      - run: |
          docker run --rm ${{ github.repository }}:test